### ISSUE TITLE
return an error on property when i try to delete an entry

### ISSUE THREAD

**Issue by Renand** [rip747/Uploadable-Files#2]
Hi..

I have e model named "product", with :

<cffunction name="init">
<cfscript>
uploadableFile(property="sample", removeOnDelete=false); 
</cfscript>
</cffunction>

and in my products controller a delete function 

<cffunction  name="delete">
    <cfscript>  
        // -------------- Initialisation du produit à supprimer
        product = model("product").findByKey(params.key);
        product.delete();

```
    // -------------- Si des erreurs sont retournées
        if ( product.hasErrors() ) {

            // -------------- On insert un message flash
            flashInsert(error="#errorMessagesFor("product")#");

            // -------------- On rend la vue "edit"
            redirectTo(action="list");

        // -------------- Si pas d'erreur   
        } else {

            // -------------- On insert un message flash
            flashInsert(success="#$('layout.successfullyDelete')#");

            // -------------- On redirige vers la liste des produits
            redirectTo(action="list");

        }
</cfscript>
```

  </cffunction>

When I delete a product, I receive an error : **Error during upload.** 
I have made a test with or whithout removeOnDelete=false, with same issue.

**Comment by Renand** [comment]
wheels 1.1.5, Uploadable-Files 0.4

**Comment by rip747** [comment]
I'll definitely look into this to confirm that this is a bug. One thing though, why are you calling product.hasErrors() after calling product.delete()? what you should be doing is checking if an object was retrieved from the database and then perform your delete. So you're delete method could be rewritten to this:

```
<cffunction name="delete">
<cfscript>
product = model("product").findByKey(params.key);
if (!IsObject(product))
{
    flashInsert(error="Invalid product");
}
else
{
    product.delete();
    flashInsert(success="#$('layout.successfullyDelete')#");
}
redirectTo(action="list");
</cfscript>
</cffunction>
```

**Comment by Renand** [comment]
Yes :) 
Thanks to open my eyes.

**Comment by Renand** [comment]
butt.... :) if i have a custom function fired by beforeDelete() and this function add an error on a particular property, ..
for the moment I will use product.clearErrors(myUploadProperty);

**Comment by rip747** [comment]
i now check to make sure that there was a post request before doing an upload. not the prettiest way, but it works

**Comment by Renand** [comment]
Hi tony, tanks for your Help, When I update the plugin to 0.5 I find a new message :

Element C:\Inetpub\wwwroot\SITES\adminOnWheels\files\temp\ is undefined in a Java object of type class coldfusion.runtime.TemplateProxy.

The error occurred in C:\Inetpub\wwwroot\SITES\adminOnWheels\plugins\uploadablefiles\uploadablefiles.cfc: line 193
Called from C:\Inetpub\wwwroot\SITES\adminOnWheels\plugins\uploadablefiles\uploadablefiles.cfc: line 77
Called from C:\Inetpub\wwwroot\SITES\adminOnWheels\wheels\global\cfml.cfm: line 174
Called from C:\Inetpub\wwwroot\SITES\adminOnWheels\wheels\model\callbacks.cfm: line 291
Called from C:\Inetpub\wwwroot\SITES\adminOnWheels\wheels\model\crud.cfm: line 830
Called from C:\Inetpub\wwwroot\SITES\adminOnWheels\wheels\global\cfml.cfm: line 174
Called from C:\Inetpub\wwwroot\SITES\adminOnWheels\wheels\model\transactions.cfm: line 53
Called from C:\Inetpub\wwwroot\SITES\adminOnWheels\wheels\model\crud.cfm: line 816
Called from C:\Inetpub\wwwroot\SITES\adminOnWheels\wheels\model\crud.cfm: line 896
Called from C:\Inetpub\wwwroot\SITES\adminOnWheels\controllers\Tissues.cfc: line 225
Called from C:\Inetpub\wwwroot\SITES\adminOnWheels\wheels\global\cfml.cfm: line 174
Called from C:\Inetpub\wwwroot\SITES\adminOnWheels\wheels\controller\processing.cfm: line 85
Called from C:\Inetpub\wwwroot\SITES\adminOnWheels\wheels\controller\processing.cfm: line 60
Called from C:\Inetpub\wwwroot\SITES\adminOnWheels\wheels\dispatch\request.cfm: line 166
Called from C:\Inetpub\wwwroot\SITES\adminOnWheels\wheels\index.cfm: line 1
Called from C:\Inetpub\wwwroot\SITES\adminOnWheels\rewrite.cfm: line 1
Called from C:\Inetpub\wwwroot\SITES\adminOnWheels\wheels\events\onrequest.cfm: line 1
191 :       <cfset var loc = {}>
192 :       <cfset loc.config = variables.wheels.class._uploadableFiles[arguments.key]>
193 :       <cfif arguments.eval && IsCustomFunction(this[loc.config['destination']])>
194 :           <cfinvoke component="#this#" method="#loc.config['destination']#" returnvariable="loc.ret">
195 :           <cfset loc.config['destination'] = loc.ret>

I will try to understand why, but my first question is :
Actually I use a temp folder defined in my model like this : destination=expandPath(application.folders.uploadTemp) // /files/temp/
And I move my file with atfersave() medhod in other destination, like this one /images/CONTROLLER_NAME/OBJECT_ID/renamed_file_name.jpg (UUID in fact)

I saw in plugin code (_getUFProperty) a way to defined a dynamic destination folder, but I don't know if it's possible to use it if I want to use ID in path.

Thanks

**Comment by rip747** [comment]
I think you're getting that error because the temp folder might not exists.
I will look more into this tonight. Please put this into a ticket on github.
When I fix the problem, would it be ok to email you the new version for
yesting?
On Oct 10, 2011 3:29 AM, "Renand" <
reply@reply.github.com>
wrote:

**Comment by Renand** [comment]
My temp foder exist. 
I will create a new issue.
THanks

**Comment by rip747** [comment]
Weird. I must have missed something when testing. :P
On Oct 10, 2011 9:16 AM, "Renand" <
reply@reply.github.com>
wrote:
