### ISSUE TITLE
maximum file size

### ISSUE THREAD

**Issue by dasDaniel** [rip747/Uploadable-Files#7]
more of a suggestion, but would be handy to limit the maximum file size.
(maybe there already is a way of handling this with a callback but I haven't figured it out yet)

**Comment by rip747** [comment]
The plugin returns the entire cffile acope which includes the siE of the
file.

**Comment by rip747** [comment]
my god i can't type on an android :P that was suppose to read:

the plugin return the entire cffile scope which includes the size of the file.
